In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("accident.csv")
df

Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
0     56  Female             27.0          No            No         1
1     69  Female             46.0          No           Yes         1
2     46    Male             46.0         Yes           Yes         0
3     32    Male            117.0          No           Yes         0
4     60  Female             40.0         Yes           Yes         0
..   ...     ...              ...         ...           ...       ...
195   69  Female            111.0          No           Yes         1
196   30  Female             51.0          No           Yes         1
197   58    Male            110.0          No           Yes         1
198   20    Male            103.0          No           Yes         1
199   56  Female             43.0          No           Yes         1

[200 rows x 6 columns]

In [2]:
df.head()

Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
0   56  Female             27.0          No            No         1
1   69  Female             46.0          No           Yes         1
2   46    Male             46.0         Yes           Yes         0
3   32    Male            117.0          No           Yes         0
4   60  Female             40.0         Yes           Yes         0

In [3]:
df.tail()

Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
195   69  Female            111.0          No           Yes         1
196   30  Female             51.0          No           Yes         1
197   58    Male            110.0          No           Yes         1
198   20    Male            103.0          No           Yes         1
199   56  Female             43.0          No           Yes         1

In [4]:
df.columns

Index(['Age', 'Gender', 'Speed_of_Impact', 'Helmet_Used', 'Seatbelt_Used',
       'Survived'],
      dtype='object')

In [5]:
df.dtypes

Age                  int64
Gender              object
Speed_of_Impact    float64
Helmet_Used         object
Seatbelt_Used       object
Survived             int64
dtype: object

In [6]:
df.isna().sum()

Age                0
Gender             1
Speed_of_Impact    3
Helmet_Used        0
Seatbelt_Used      0
Survived           0
dtype: int64

In [7]:
df["Gender"].unique()

array(['Female', 'Male', nan], dtype=object)

In [8]:
df["Gender"].value_counts()

Gender
Female    110
Male       89
Name: count, dtype: int64

In [9]:
df["Speed_of_Impact"].unique()

array([ 27.,  46., 117.,  40.,  49., 116.,  47.,  83.,  88.,  80.,  67.,
        38.,  23.,  nan,  68.,  36., 111., 112.,  65.,  25., 118.,  56.,
        43.,  72., 114.,  79.,  82., 104.,  51., 106.,  52.,  86.,  37.,
        44.,  73.,  77.,  66., 105.,  42.,  85.,  21., 109.,  28.,  62.,
        58.,  61.,  45.,  69.,  32.,  26.,  76.,  55.,  64.,  39.,  84.,
        35.,  33.,  95.,  34.,  70.,  81.,  41.,  71.,  89.,  24.,  87.,
       115., 113.,  74.,  59.,  31.,  20.,  53., 108.,  48.,  97., 119.,
        29.,  99., 110., 103.])

In [10]:
df["Helmet_Used"].value_counts()

Helmet_Used
Yes    111
No      89
Name: count, dtype: int64

In [11]:
df["Seatbelt_Used"].value_counts()

Seatbelt_Used
Yes    111
No      89
Name: count, dtype: int64

In [13]:
df["Gender"]=df["Gender"].fillna(df["Gender"].mode()[0])
df["Speed_of_Impact"]=df["Speed_of_Impact"].fillna(df["Speed_of_Impact"].mean())


In [14]:
df.isna().sum()

Age                0
Gender             0
Speed_of_Impact    0
Helmet_Used        0
Seatbelt_Used      0
Survived           0
dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
for i in df.columns:
    if df[i].dtype=="object":
        df[i]=lab.fit_transform(df[i])
df


Age  Gender  Speed_of_Impact  Helmet_Used  Seatbelt_Used  Survived
0     56       0             27.0            0              0         1
1     69       0             46.0            0              1         1
2     46       1             46.0            1              1         0
3     32       1            117.0            0              1         0
4     60       0             40.0            1              1         0
..   ...     ...              ...          ...            ...       ...
195   69       0            111.0            0              1         1
196   30       0             51.0            0              1         1
197   58       1            110.0            0              1         1
198   20       1            103.0            0              1         1
199   56       0             43.0            0              1         1

[200 rows x 6 columns]

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[ 50.        ,   0.        ,  66.        ,   0.        ,
          0.        ],
       [ 57.        ,   0.        ,  69.        ,   1.        ,
          0.        ],
       [ 27.        ,   0.        ,  27.        ,   1.        ,
          0.        ],
       [ 68.        ,   0.        ,  44.        ,   0.        ,
          1.        ],
       [ 39.        ,   1.        ,  68.        ,   0.        ,
          0.        ],
       [ 25.        ,   1.        ,  49.        ,   1.        ,
          1.        ],
       [ 50.        ,   1.        ,  38.        ,   0.        ,
          1.        ],
       [ 41.        ,   1.        ,  73.        ,   0.        ,
          0.        ],
       [ 21.        ,   1.        ,  43.        ,   0.        ,
          0.        ],
       [ 67.        ,   0.        , 118.        ,   1.        ,
          0.        ],
       [ 19.        ,   1.        ,  46.        ,   0.        ,
          1.        ],
       [ 25.        ,   0.        , 111.   

In [ ]:
x_test

array([[ 24.        ,   0.        ,  52.        ,   0.        ,
          0.        ],
       [ 20.        ,   1.        ,  86.        ,   1.        ,
          1.        ],
       [ 33.        ,   1.        , 116.        ,   0.        ,
          0.        ],
       [ 42.        ,   1.        ,  61.        ,   0.        ,
          1.        ],
       [ 61.        ,   0.        ,  29.        ,   1.        ,
          1.        ],
       [ 20.        ,   1.        , 103.        ,   0.        ,
          1.        ],
       [ 42.        ,   1.        ,  81.        ,   0.        ,
          1.        ],
       [ 60.        ,   0.        ,  40.        ,   1.        ,
          1.        ],
       [ 42.        ,   1.        ,  70.44162437,   1.        ,
          0.        ],
       [ 32.        ,   1.        ,  35.        ,   0.        ,
          0.        ],
       [ 53.        ,   1.        ,  67.        ,   1.        ,
          0.        ],
       [ 19.        ,   0.        ,  36.   

In [ ]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [ ]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)   
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_test

array([[-1.38977782, -0.87872174, -0.58557673, -1.1055416 , -1.1055416 ],
       [-1.66161701,  1.13801668,  0.52207672,  0.90453403,  0.90453403],
       [-0.77813966,  1.13801668,  1.49941799, -1.1055416 , -1.1055416 ],
       [-0.1665015 ,  1.13801668, -0.29237435, -1.1055416 ,  0.90453403],
       [ 1.12473462, -0.87872174, -1.33487171,  0.90453403,  0.90453403],
       [-1.66161701,  1.13801668,  1.07590344, -1.1055416 ,  0.90453403],
       [-0.1665015 ,  1.13801668,  0.3591865 , -1.1055416 ,  0.90453403],
       [ 1.05677482, -0.87872174, -0.97651324,  0.90453403,  0.90453403],
       [-0.1665015 ,  1.13801668,  0.01521529,  0.90453403, -1.1055416 ],
       [-0.84609946,  1.13801668, -1.13940345, -1.1055416 , -1.1055416 ],
       [ 0.58105625,  1.13801668, -0.09690609,  0.90453403, -1.1055416 ],
       [-1.7295768 , -0.87872174, -1.10682541,  0.90453403,  0.90453403],
       [-1.11793864,  1.13801668,  0.32660846,  0.90453403,  0.90453403],
       [-0.77813966,  1.13801668,  0.3

In [ ]:
x_train

array([[ 3.77176867e-01, -8.78721741e-01, -1.29484135e-01,
        -1.10554160e+00, -1.10554160e+00],
       [ 8.52895437e-01, -8.78721741e-01, -3.17500074e-02,
         9.04534034e-01, -1.10554160e+00],
       [-1.18589844e+00, -8.78721741e-01, -1.40002779e+00,
         9.04534034e-01, -1.10554160e+00],
       [ 1.60045319e+00, -8.78721741e-01, -8.46201070e-01,
        -1.10554160e+00,  9.04534034e-01],
       [-3.70380887e-01,  1.13801668e+00, -6.43280499e-02,
        -1.10554160e+00, -1.10554160e+00],
       [-1.32181803e+00,  1.13801668e+00, -6.83310857e-01,
         9.04534034e-01,  9.04534034e-01],
       [ 3.77176867e-01,  1.13801668e+00, -1.04166932e+00,
        -1.10554160e+00,  9.04534034e-01],
       [-2.34461296e-01,  1.13801668e+00,  9.85621626e-02,
        -1.10554160e+00, -1.10554160e+00],
       [-1.59365721e+00,  1.13801668e+00, -8.78779112e-01,
        -1.10554160e+00, -1.10554160e+00],
       [ 1.53249340e+00, -8.78721741e-01,  1.56457407e+00,
         9.04534034e-01

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=7)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[15, 18],
       [11, 16]])

In [ ]:
score=accuracy_score(y_test,y_pred)
score

0.5166666666666667