In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv("heart.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0     125.0   212    0      NaN    168.0      0      1.0   
1      53    1   0     140.0   203    1      0.0    155.0      1      3.1   
2      70    1   0     145.0   174    0      1.0    125.0      1      2.6   
3      61    1   0     148.0   203    0      1.0      NaN      0      0.0   
4      62    0   0     138.0   294    1      1.0    106.0      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1     140.0   221    0      1.0    164.0      1      0.0   
1021   60    1   0     125.0   258    0      0.0    141.0      1      2.8   
1022   47    1   0     110.0   275    0      0.0    118.0      1      1.0   
1023   50    0   0     110.0   254    0      0.0    159.0      0      0.0   
1024   54    1   0     120.0   188    0      1.0    113.0      0      1.4   

      slope   ca  thal  target  
0         2  2.0   3.0       0  
1         0  0.0   3.0       0  
2         0  0.0   3.0       0  
3         2  1.0   3.0       0  
4         1  3.0   2.0       0  
...     ...  ...   ...     ...  
1020      2  0.0   2.0       1  
1021      1  1.0   3.0       0  
1022      1  1.0   2.0       0  
1023      2  0.0   2.0       1  
1024      1  1.0   3.0       0  

[1025 rows x 14 columns]

In [3]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0     125.0   212    0      NaN    168.0      0      1.0      2   
1   53    1   0     140.0   203    1      0.0    155.0      1      3.1      0   
2   70    1   0     145.0   174    0      1.0    125.0      1      2.6      0   
3   61    1   0     148.0   203    0      1.0      NaN      0      0.0      2   
4   62    0   0     138.0   294    1      1.0    106.0      0      1.9      1   

    ca  thal  target  
0  2.0   3.0       0  
1  0.0   3.0       0  
2  0.0   3.0       0  
3  1.0   3.0       0  
4  3.0   2.0       0

In [4]:
df.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1   1     140.0   221    0      1.0    164.0      1      0.0   
1021   60    1   0     125.0   258    0      0.0    141.0      1      2.8   
1022   47    1   0     110.0   275    0      0.0    118.0      1      1.0   
1023   50    0   0     110.0   254    0      0.0    159.0      0      0.0   
1024   54    1   0     120.0   188    0      1.0    113.0      0      1.4   

      slope   ca  thal  target  
1020      2  0.0   2.0       1  
1021      1  1.0   3.0       0  
1022      1  1.0   2.0       0  
1023      2  0.0   2.0       1  
1024      1  1.0   3.0       0

In [5]:
df.shape

(1025, 14)

In [6]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [7]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps    float64
chol          int64
fbs           int64
restecg     float64
thalach     float64
exang         int64
oldpeak     float64
slope         int64
ca          float64
thal        float64
target        int64
dtype: object

In [8]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     1
thalach     1
exang       0
oldpeak     0
slope       0
ca          2
thal        1
target      0
dtype: int64

In [9]:
x=df["trestbps"].unique()
x

array([125., 140., 145., 148., 138., 100., 114., 160., 120., 122., 112.,
       132., 118., 128.,  nan, 124., 106., 104., 135., 130., 136., 180.,
       129., 150., 178., 146., 117., 152., 154., 170., 134., 174., 144.,
       108., 123., 110., 142., 126., 192., 115.,  94., 200., 165., 102.,
       105., 155., 172., 164., 156., 101.])

In [10]:
x1=df["trestbps"].mean()
df["trestbps"].fillna(x1,inplace=True)

y1=df["restecg"].mode() [0]
df["restecg"].fillna(y1,inplace=True)

z1=df["thalach"].mean()
df["thalach"].fillna(z1,inplace=True)

a1=df["ca"].mode() [0]
df["ca"].fillna(a1,inplace=True)

b1=df["thal"].mode() [0]
df["thal"].fillna(b1,inplace=True)

# df["trestbps"]=df["trestbps"].fillna(df["trestbps"].mean())

/var/folders/4q/dkk696ts13gf56vqh_wpsv200000gn/T/ipykernel_1514/2159502758.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["trestbps"].fillna(x1,inplace=True)
/var/folders/4q/dkk696ts13gf56vqh_wpsv200000gn/T/ipykernel_1514/2159502758.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves a

In [11]:
y=df["restecg"].unique()
y


array([1., 0., 2.])

In [12]:
z=df["thalach"].unique()
z

array([168.        , 155.        , 125.        , 149.10253906,
       106.        , 122.        , 140.        , 145.        ,
       144.        , 116.        , 136.        , 192.        ,
       156.        , 142.        , 109.        , 162.        ,
       165.        , 148.        , 172.        , 173.        ,
       146.        , 179.        , 152.        , 117.        ,
       115.        , 112.        , 163.        , 147.        ,
       182.        , 105.        , 150.        , 151.        ,
       169.        , 166.        , 178.        , 132.        ,
       160.        , 123.        , 139.        , 111.        ,
       180.        , 164.        , 202.        , 157.        ,
       159.        , 170.        , 138.        , 175.        ,
       158.        , 126.        , 143.        , 141.        ,
       167.        ,  95.        , 190.        , 118.        ,
       103.        , 181.        , 108.        , 177.        ,
       134.        , 120.        , 171.        , 149.  

In [13]:
a=df["ca"].unique()
a

array([2., 0., 1., 3., 4.])

In [14]:
b=df["thal"].unique()
b

array([3., 2., 1., 0.])

In [15]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [16]:
c=df.iloc[:,:-1].values
c

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]], shape=(1025, 13))

In [17]:
d=df.iloc[:,-1].values
d

array([0, 0, 0, ..., 0, 1, 0], shape=(1025,))

In [18]:
from sklearn.model_selection import train_test_split
c_train,c_test,d_train,d_test=train_test_split(c,d,test_size=0.30,random_state=0)
c_train

array([[57.,  1.,  2., ...,  2.,  0.,  2.],
       [59.,  1.,  0., ...,  1.,  2.,  1.],
       [71.,  0.,  0., ...,  1.,  0.,  2.],
       ...,
       [65.,  1.,  3., ...,  1.,  1.,  2.],
       [67.,  1.,  0., ...,  1.,  0.,  2.],
       [60.,  1.,  2., ...,  1.,  0.,  2.]], shape=(717, 13))

In [19]:
c_test

array([[44.,  1.,  2., ...,  2.,  0.,  2.],
       [58.,  0.,  1., ...,  2.,  2.,  2.],
       [63.,  1.,  0., ...,  2.,  2.,  3.],
       ...,
       [56.,  1.,  2., ...,  1.,  1.,  1.],
       [57.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]], shape=(308, 13))

In [20]:
d_train

array([1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,

In [21]:
d_test

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,

In [22]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(c_train)   
c_train=scaler.transform(c_train)
c_test=scaler.transform(c_test)
c_test

array([[-1.16453806,  0.65226323,  1.02564169, ...,  0.9790949 ,
        -0.73603133, -0.51108759],
       [ 0.38807624, -1.53312338,  0.05419507, ...,  0.9790949 ,
         1.21132832, -0.51108759],
       [ 0.94258134,  0.65226323, -0.91725155, ...,  0.9790949 ,
         1.21132832,  1.10322872],
       ...,
       [ 0.16627419,  0.65226323,  1.02564169, ..., -0.66111782,
         0.23764849, -2.12540389],
       [ 0.27717522, -1.53312338, -0.91725155, ...,  0.9790949 ,
        -0.73603133, -0.51108759],
       [-0.05552785,  0.65226323, -0.91725155, ..., -0.66111782,
         0.23764849,  1.10322872]], shape=(308, 13))

In [23]:
c_train

array([[ 0.27717522,  0.65226323,  1.02564169, ...,  0.9790949 ,
        -0.73603133, -0.51108759],
       [ 0.49897726,  0.65226323, -0.91725155, ..., -0.66111782,
         1.21132832, -2.12540389],
       [ 1.82978951, -1.53312338, -0.91725155, ..., -0.66111782,
        -0.73603133, -0.51108759],
       ...,
       [ 1.16438338,  0.65226323,  1.99708831, ..., -0.66111782,
         0.23764849, -0.51108759],
       [ 1.38618543,  0.65226323, -0.91725155, ..., -0.66111782,
        -0.73603133, -0.51108759],
       [ 0.60987828,  0.65226323,  1.02564169, ..., -0.66111782,
        -0.73603133, -0.51108759]], shape=(717, 13))

In [24]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=7)
model.fit(c_train,d_train)
d_pred=model.predict(c_test)
d_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,

In [25]:
d_test

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,

In [26]:
print(model.predict(scaler.transform([[42,1,1,137.0,223,0,1.0,145.0,1,2.5,2,2.0,2.0]])))

[1]


In [27]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(d_pred,d_test)
cm

array([[122,  16],
       [ 23, 147]])

In [28]:
from sklearn.metrics import accuracy_score
score=accuracy_score(d_pred,d_test)
score

0.8733766233766234

In [29]:
#if values of multiple columns are filled using mean

# for i in df.columns:
#     if df[i].dtype != 'object':  # Ensure it's a numerical column
#         mean_value = df[i].mean()  # Calculate the column mean
#         df[i].fillna(mean_value, inplace=True)

In [30]:
from sklearn.metrics import classification_report
cr=classification_report(d_test,d_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.88      0.84      0.86       145
           1       0.86      0.90      0.88       163

    accuracy                           0.87       308
   macro avg       0.87      0.87      0.87       308
weighted avg       0.87      0.87      0.87       308

