In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("manufacturing.csv")
df

Temperature (°C)  Pressure (kPa)  Temperature x Pressure  \
0           209.762701        8.050855             1688.769167   
1           243.037873       15.812068             3842.931469   
2           220.552675        7.843130             1729.823314   
3           208.976637       23.786089             4970.736918   
4           184.730960       15.797812             2918.345014   
...                ...             ...                     ...   
3952        156.811578       21.794290             3417.596965   
3953        197.850406        8.291704             1640.516924   
3954        241.357144       16.391910             3956.304672   
3955        209.040239       23.809936             4977.234763   
3956        163.359996       24.332133             3974.897121   

      Material Fusion Metric  Material Transformation Metric  Quality Rating  
0               44522.217074                    9.229576e+06       99.999971  
1               63020.764997                    1.435537e+07       99.985703  
2               49125.950249                    1.072839e+07       99.999758  
3               57128.881547                    9.125702e+06       99.999975  
4               38068.201283                    6.303792e+06      100.000000  
...                      ...                             ...             ...  
3952            34941.963896                    3.855501e+06      100.000000  
3953            39714.857236                    7.744742e+06       99.999997  
3954            62657.690952                    1.405957e+07       99.989318  
3955            57195.985528                    9.134036e+06       99.999975  
3956            41092.392901                    4.358913e+06      100.000000  

[3957 rows x 6 columns]

In [3]:
df.head()

Temperature (°C)  Pressure (kPa)  Temperature x Pressure  \
0        209.762701        8.050855             1688.769167   
1        243.037873       15.812068             3842.931469   
2        220.552675        7.843130             1729.823314   
3        208.976637       23.786089             4970.736918   
4        184.730960       15.797812             2918.345014   

   Material Fusion Metric  Material Transformation Metric  Quality Rating  
0            44522.217074                    9.229576e+06       99.999971  
1            63020.764997                    1.435537e+07       99.985703  
2            49125.950249                    1.072839e+07       99.999758  
3            57128.881547                    9.125702e+06       99.999975  
4            38068.201283                    6.303792e+06      100.000000

In [4]:
df.tail()

Temperature (°C)  Pressure (kPa)  Temperature x Pressure  \
3952        156.811578       21.794290             3417.596965   
3953        197.850406        8.291704             1640.516924   
3954        241.357144       16.391910             3956.304672   
3955        209.040239       23.809936             4977.234763   
3956        163.359996       24.332133             3974.897121   

      Material Fusion Metric  Material Transformation Metric  Quality Rating  
3952            34941.963896                    3.855501e+06      100.000000  
3953            39714.857236                    7.744742e+06       99.999997  
3954            62657.690952                    1.405957e+07       99.989318  
3955            57195.985528                    9.134036e+06       99.999975  
3956            41092.392901                    4.358913e+06      100.000000

In [5]:
df.isna().sum()

Temperature (°C)                  0
Pressure (kPa)                    0
Temperature x Pressure            0
Material Fusion Metric            0
Material Transformation Metric    0
Quality Rating                    0
dtype: int64

In [6]:
df.dtypes

Temperature (°C)                  float64
Pressure (kPa)                    float64
Temperature x Pressure            float64
Material Fusion Metric            float64
Material Transformation Metric    float64
Quality Rating                    float64
dtype: object

In [7]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)
x_train

Temperature (°C)  Pressure (kPa)  Temperature x Pressure  \
98          265.788006       22.812104             6063.183507   
1446        281.579692       10.898344             3068.752215   
1525        281.649676       16.711005             4706.649020   
40          171.901580       21.600059             3713.084262   
3525        212.382292        9.999574             2123.732409   
...                ...             ...                     ...   
835         195.876910       11.015577             2157.697202   
3264        137.036400       14.808613             2029.319036   
1653        205.663025       23.757125             4885.962265   
2607        272.433253        8.157178             2222.286575   
2732        251.353121       13.812065             3471.705561   

      Material Fusion Metric  Material Transformation Metric  
98              82514.501772                    1.877561e+07  
1446            80581.561347                    2.232552e+07  
1525            83993.216166                    2.234201e+07  
40              39627.931742                    5.079251e+06  
3525            46106.109930                    9.579666e+06  
...                      ...                             ...  
835             39704.426320                    7.515238e+06  
3264            22026.430148                    2.573184e+06  
1653            55705.825363                    8.698422e+06  
2607            74762.652564                    2.021990e+07  
2732            65813.362336                    1.587990e+07  

[2769 rows x 5 columns]

In [9]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred


array([102.68707798, 104.99892029,  88.86276693, ...,  73.53442614,
       102.93290408,  94.31054566], shape=(1188,))

In [10]:
from sklearn.metrics import mean_absolute_percentage_error,r2_score
mape=mean_absolute_percentage_error(y_test,y_pred)
mape

0.18611194558569422

In [11]:
score=r2_score(y_test,y_pred)
score

0.5232024177259642

In [12]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=3)
X_train_poly = poly.fit_transform(x_train)
X_test_poly = poly.transform(x_test)
X_train_poly


array([[1.00000000e+00, 2.65788006e+02, 2.28121035e+01, ...,
        1.27836438e+17, 2.90883094e+19, 6.61884633e+21],
       [1.00000000e+00, 2.81579692e+02, 1.08983435e+01, ...,
        1.44968295e+17, 4.01641916e+19, 1.11276902e+22],
       [1.00000000e+00, 2.81649676e+02, 1.67110046e+01, ...,
        1.57619796e+17, 4.19265270e+19, 1.11523661e+22],
       ...,
       [1.00000000e+00, 2.05663025e+02, 2.37571253e+01, ...,
        2.69924129e+16, 4.21484470e+18, 6.58144788e+20],
       [1.00000000e+00, 2.72433253e+02, 8.15717812e+00, ...,
        1.13018184e+17, 3.05662770e+19, 8.26678730e+21],
       [1.00000000e+00, 2.51353121e+02, 1.38120647e+01, ...,
        6.87821565e+16, 1.65962260e+19, 4.00445013e+21]], shape=(2769, 56))

In [13]:
model1=LinearRegression()
model1.fit(X_train_poly,y_train)
y_pred1=model1.predict(X_test_poly)
y_pred1

array([101.00090797,  99.93463519, 102.8645794 , ...,  43.38734041,
       100.79148358, 101.26606946], shape=(1188,))

In [14]:
print(mean_absolute_percentage_error(y_test,y_pred1))

0.060617100511875355


In [15]:
print(r2_score(y_test,y_pred1))

0.9553309967091292
