In [182]:
import numpy as np
import pandas as pd
df=pd.read_csv("accident.csv")
df

Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
0     56  Female             27.0          No            No         1
1     69  Female             46.0          No           Yes         1
2     46    Male             46.0         Yes           Yes         0
3     32    Male            117.0          No           Yes         0
4     60  Female             40.0         Yes           Yes         0
..   ...     ...              ...         ...           ...       ...
195   69  Female            111.0          No           Yes         1
196   30  Female             51.0          No           Yes         1
197   58    Male            110.0          No           Yes         1
198   20    Male            103.0          No           Yes         1
199   56  Female             43.0          No           Yes         1

[200 rows x 6 columns]

In [183]:
df.head()

Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
0   56  Female             27.0          No            No         1
1   69  Female             46.0          No           Yes         1
2   46    Male             46.0         Yes           Yes         0
3   32    Male            117.0          No           Yes         0
4   60  Female             40.0         Yes           Yes         0

In [184]:
df.tail()

Age  Gender  Speed_of_Impact Helmet_Used Seatbelt_Used  Survived
195   69  Female            111.0          No           Yes         1
196   30  Female             51.0          No           Yes         1
197   58    Male            110.0          No           Yes         1
198   20    Male            103.0          No           Yes         1
199   56  Female             43.0          No           Yes         1

In [185]:
df.columns

Index(['Age', 'Gender', 'Speed_of_Impact', 'Helmet_Used', 'Seatbelt_Used',
       'Survived'],
      dtype='object')

In [186]:
df.dtypes

Age                  int64
Gender              object
Speed_of_Impact    float64
Helmet_Used         object
Seatbelt_Used       object
Survived             int64
dtype: object

In [187]:
df.isna().sum()

Age                0
Gender             1
Speed_of_Impact    3
Helmet_Used        0
Seatbelt_Used      0
Survived           0
dtype: int64

In [188]:
df["Gender"].unique()


array(['Female', 'Male', nan], dtype=object)

In [189]:
df["Gender"].value_counts()

Gender
Female    110
Male       89
Name: count, dtype: int64

In [190]:
df["Speed_of_Impact"].unique()

array([ 27.,  46., 117.,  40.,  49., 116.,  47.,  83.,  88.,  80.,  67.,
        38.,  23.,  nan,  68.,  36., 111., 112.,  65.,  25., 118.,  56.,
        43.,  72., 114.,  79.,  82., 104.,  51., 106.,  52.,  86.,  37.,
        44.,  73.,  77.,  66., 105.,  42.,  85.,  21., 109.,  28.,  62.,
        58.,  61.,  45.,  69.,  32.,  26.,  76.,  55.,  64.,  39.,  84.,
        35.,  33.,  95.,  34.,  70.,  81.,  41.,  71.,  89.,  24.,  87.,
       115., 113.,  74.,  59.,  31.,  20.,  53., 108.,  48.,  97., 119.,
        29.,  99., 110., 103.])

In [191]:
df["Helmet_Used"].value_counts()

Helmet_Used
Yes    111
No      89
Name: count, dtype: int64

In [192]:
df["Seatbelt_Used"].value_counts()

Seatbelt_Used
Yes    111
No      89
Name: count, dtype: int64

In [193]:
df["Gender"]=df["Gender"].fillna(df["Gender"].mode()[0])
df["Speed_of_Impact"]=df["Speed_of_Impact"].fillna(df["Speed_of_Impact"].mean())


In [194]:
df.isna().sum()

Age                0
Gender             0
Speed_of_Impact    0
Helmet_Used        0
Seatbelt_Used      0
Survived           0
dtype: int64

In [195]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
for i in df.columns:
     if df[i].dtype== 'object':  
         df[i]=lab.fit_transform(df[i])
df

Age  Gender  Speed_of_Impact  Helmet_Used  Seatbelt_Used  Survived
0     56       0             27.0            0              0         1
1     69       0             46.0            0              1         1
2     46       1             46.0            1              1         0
3     32       1            117.0            0              1         0
4     60       0             40.0            1              1         0
..   ...     ...              ...          ...            ...       ...
195   69       0            111.0            0              1         1
196   30       0             51.0            0              1         1
197   58       1            110.0            0              1         1
198   20       1            103.0            0              1         1
199   56       0             43.0            0              1         1

[200 rows x 6 columns]

In [196]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [197]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)
x_train

array([[ 54.        ,   1.        , 109.        ,   1.        ,
          0.        ],
       [ 62.        ,   0.        ,  41.        ,   1.        ,
          0.        ],
       [ 23.        ,   1.        ,  53.        ,   1.        ,
          1.        ],
       [ 41.        ,   1.        ,  70.44162437,   1.        ,
          0.        ],
       [ 43.        ,   1.        ,  95.        ,   0.        ,
          0.        ],
       [ 64.        ,   1.        ,  44.        ,   1.        ,
          1.        ],
       [ 19.        ,   1.        ,  46.        ,   0.        ,
          1.        ],
       [ 47.        ,   0.        ,  66.        ,   1.        ,
          1.        ],
       [ 67.        ,   0.        , 105.        ,   1.        ,
          0.        ],
       [ 40.        ,   0.        ,  85.        ,   0.        ,
          1.        ],
       [ 52.        ,   0.        ,  20.        ,   0.        ,
          0.        ],
       [ 62.        ,   0.        , 105.   

In [198]:
x_test

array([[ 19.,   0.,  36.,   1.,   1.],
       [ 46.,   0., 109.,   1.,   0.],
       [ 61.,   1., 116.,   1.,   0.],
       [ 46.,   1.,  77.,   1.,   1.],
       [ 45.,   0.,  42.,   0.,   0.],
       [ 45.,   1.,  71.,   0.,   0.],
       [ 25.,   1.,  49.,   1.,   1.],
       [ 43.,   1.,  80.,   1.,   1.],
       [ 41.,   1.,  67.,   1.,   0.],
       [ 32.,   0.,  86.,   0.,   0.],
       [ 64.,   1.,  67.,   1.,   0.],
       [ 29.,   0.,  36.,   1.,   0.],
       [ 62.,   0., 119.,   1.,   1.],
       [ 59.,   0.,  45.,   1.,   1.],
       [ 31.,   1.,  33.,   1.,   1.],
       [ 56.,   1.,  47.,   1.,   1.],
       [ 45.,   1.,  79.,   0.,   1.],
       [ 41.,   1.,  74.,   0.,   1.],
       [ 68.,   0.,  51.,   0.,   0.],
       [ 35.,   1.,  55.,   0.,   0.],
       [ 45.,   1., 114.,   0.,   0.],
       [ 22.,   1.,  35.,   0.,   0.],
       [ 26.,   1.,  77.,   1.,   1.],
       [ 66.,   1.,  48.,   1.,   0.],
       [ 25.,   1.,  62.,   1.,   0.],
       [ 26.,   0.,  49.,

In [199]:
y_train

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0])

In [200]:
y_test

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0])

In [201]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.70550493,  1.15470054,  1.20828426,  0.97182532, -1.13801668],
       [ 1.25233228, -0.8660254 , -1.02846333,  0.97182532, -1.13801668],
       [-1.41345105,  1.15470054, -0.63374316,  0.97182532,  0.87872174],
       [-0.18308951,  1.15470054, -0.06002976,  0.97182532, -1.13801668],
       [-0.04638268,  1.15470054,  0.74777741, -1.02899151, -1.13801668],
       [ 1.38903912,  1.15470054, -0.92978328,  0.97182532,  0.87872174],
       [-1.68686473,  1.15470054, -0.86399659, -1.02899151,  0.87872174],
       [ 0.227031  , -0.8660254 , -0.20612965,  0.97182532,  0.87872174],
       [ 1.59409937, -0.8660254 ,  1.07671088,  0.97182532, -1.13801668],
       [-0.25144293, -0.8660254 ,  0.41884394, -1.02899151,  0.87872174],
       [ 0.56879809, -0.8660254 , -1.71922361, -1.02899151, -1.13801668],
       [ 1.25233228, -0.8660254 ,  1.07671088,  0.97182532, -1.13801668],
       [ 0.56879809,  1.15470054, -1.71922361,  0.97182532, -1.13801668],
       [-1.75521815,  1.15470054, -0.0

In [202]:
x_test

array([[-1.68686473, -0.8660254 , -1.19293006,  0.97182532,  0.87872174],
       [ 0.15867758, -0.8660254 ,  1.20828426,  0.97182532, -1.13801668],
       [ 1.18397886,  1.15470054,  1.43853769,  0.97182532, -1.13801668],
       [ 0.15867758,  1.15470054,  0.15569716,  0.97182532,  0.87872174],
       [ 0.09032416, -0.8660254 , -0.99556998, -1.02899151, -1.13801668],
       [ 0.09032416,  1.15470054, -0.04166292, -1.02899151, -1.13801668],
       [-1.27674422,  1.15470054, -0.76531655,  0.97182532,  0.87872174],
       [-0.04638268,  1.15470054,  0.2543772 ,  0.97182532,  0.87872174],
       [-0.18308951,  1.15470054, -0.17323631,  0.97182532, -1.13801668],
       [-0.79827028, -0.8660254 ,  0.45173729, -1.02899151, -1.13801668],
       [ 1.38903912,  1.15470054, -0.17323631,  0.97182532, -1.13801668],
       [-1.00333054, -0.8660254 , -1.19293006,  0.97182532, -1.13801668],
       [ 1.25233228, -0.8660254 ,  1.53721773,  0.97182532,  0.87872174],
       [ 1.04727202, -0.8660254 , -0.8

In [203]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0])

In [204]:
y_test

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0])

In [205]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[20,  7],
       [21, 12]])

In [206]:
score=accuracy_score(y_test,y_pred)
score

0.5333333333333333