In [38]:
import numpy as np
import pandas as pd
df=pd.read_csv("alzheimers_prediction_dataset.csv")
df

Country  Age  Gender  Education Level   BMI  \
0             Spain   90    Male                1  33.0   
1         Argentina   72    Male                7  29.9   
2      South Africa   86  Female               19  22.9   
3             China   53    Male               17  31.2   
4            Sweden   58  Female                3  30.0   
...             ...  ...     ...              ...   ...   
74278        Russia   60  Female                3  22.6   
74279            UK   58    Male               18  30.6   
74280         Spain   57  Female               13  28.2   
74281        Brazil   73  Female                7  29.0   
74282        Norway   57  Female                1  31.7   

      Physical Activity Level Smoking Status Alcohol Consumption Diabetes  \
0                      Medium          Never        Occasionally       No   
1                      Medium         Former               Never       No   
2                        High        Current        Occasionally       No   
3                         Low          Never           Regularly      Yes   
4                        High         Former               Never      Yes   
...                       ...            ...                 ...      ...   
74278                    High         Former               Never       No   
74279                     Low          Never        Occasionally      Yes   
74280                  Medium          Never           Regularly       No   
74281                     Low          Never           Regularly       No   
74282                     Low        Current           Regularly       No   

      Hypertension  ... Dietary Habits Air Pollution Exposure  \
0               No  ...        Healthy                   High   
1               No  ...        Healthy                 Medium   
2              Yes  ...        Average                 Medium   
3               No  ...        Healthy                 Medium   
4               No  ...      Unhealthy                   High   
...            ...  ...            ...                    ...   
74278           No  ...        Average                   High   
74279           No  ...        Average                 Medium   
74280           No  ...        Healthy                    Low   
74281           No  ...        Healthy                    Low   
74282           No  ...        Average                    Low   

       Employment Status Marital Status Genetic Risk Factor (APOE-ε4 allele)  \
0                Retired         Single                                   No   
1             Unemployed        Widowed                                   No   
2               Employed         Single                                   No   
3                Retired         Single                                   No   
4               Employed        Married                                   No   
...                  ...            ...                                  ...   
74278         Unemployed        Widowed                                   No   
74279         Unemployed         Single                                   No   
74280           Employed         Single                                  Yes   
74281           Employed        Widowed                                   No   
74282         Unemployed         Single                                   No   

      Social Engagement Level Income Level Stress Levels  \
0                         Low       Medium          High   
1                        High          Low          High   
2                         Low       Medium          High   
3                        High       Medium           Low   
4                         Low       Medium          High   
...                       ...          ...           ...   
74278                  Medium         High        Medium   
74279                  Medium         High          High   
74280                    High          Low           Low   
74281                     Low       

In [39]:
df.head()

Country  Age  Gender  Education Level   BMI Physical Activity Level  \
0         Spain   90    Male                1  33.0                  Medium   
1     Argentina   72    Male                7  29.9                  Medium   
2  South Africa   86  Female               19  22.9                    High   
3         China   53    Male               17  31.2                     Low   
4        Sweden   58  Female                3  30.0                    High   

  Smoking Status Alcohol Consumption Diabetes Hypertension  ...  \
0          Never        Occasionally       No           No  ...   
1         Former               Never       No           No  ...   
2        Current        Occasionally       No          Yes  ...   
3          Never           Regularly      Yes           No  ...   
4         Former               Never      Yes           No  ...   

  Dietary Habits Air Pollution Exposure  Employment Status Marital Status  \
0        Healthy                   High            Retired         Single   
1        Healthy                 Medium         Unemployed        Widowed   
2        Average                 Medium           Employed         Single   
3        Healthy                 Medium            Retired         Single   
4      Unhealthy                   High           Employed        Married   

  Genetic Risk Factor (APOE-ε4 allele) Social Engagement Level Income Level  \
0                                   No                     Low       Medium   
1                                   No                    High          Low   
2                                   No                     Low       Medium   
3                                   No                    High       Medium   
4                                   No                     Low       Medium   

  Stress Levels Urban vs Rural Living Alzheimer’s Diagnosis  
0          High                 Urban                    No  
1          High                 Urban                    No  
2          High                 Rural                    No  
3           Low                 Rural                    No  
4          High                 Rural                    No  

[5 rows x 25 columns]

In [40]:
df.tail()

Country  Age  Gender  Education Level   BMI Physical Activity Level  \
74278  Russia   60  Female                3  22.6                    High   
74279      UK   58    Male               18  30.6                     Low   
74280   Spain   57  Female               13  28.2                  Medium   
74281  Brazil   73  Female                7  29.0                     Low   
74282  Norway   57  Female                1  31.7                     Low   

      Smoking Status Alcohol Consumption Diabetes Hypertension  ...  \
74278         Former               Never       No           No  ...   
74279          Never        Occasionally      Yes           No  ...   
74280          Never           Regularly       No           No  ...   
74281          Never           Regularly       No           No  ...   
74282        Current           Regularly       No           No  ...   

      Dietary Habits Air Pollution Exposure  Employment Status Marital Status  \
74278        Average                   High         Unemployed        Widowed   
74279        Average                 Medium         Unemployed         Single   
74280        Healthy                    Low           Employed         Single   
74281        Healthy                    Low           Employed        Widowed   
74282        Average                    Low         Unemployed         Single   

      Genetic Risk Factor (APOE-ε4 allele) Social Engagement Level  \
74278                                   No                  Medium   
74279                                   No                  Medium   
74280                                  Yes                    High   
74281                                   No                     Low   
74282                                   No                     Low   

      Income Level Stress Levels Urban vs Rural Living Alzheimer’s Diagnosis  
74278         High        Medium                 Rural                    No  
74279         High          High                 Rural                    No  
74280          Low           Low                 Rural                    No  
74281          Low          High                 Rural                    No  
74282       Medium        Medium                 Urban                    No  

[5 rows x 25 columns]

In [41]:
df.columns

Index(['Country', 'Age', 'Gender', 'Education Level', 'BMI',
       'Physical Activity Level', 'Smoking Status', 'Alcohol Consumption',
       'Diabetes', 'Hypertension', 'Cholesterol Level',
       'Family History of Alzheimer’s', 'Cognitive Test Score',
       'Depression Level', 'Sleep Quality', 'Dietary Habits',
       'Air Pollution Exposure', 'Employment Status', 'Marital Status',
       'Genetic Risk Factor (APOE-ε4 allele)', 'Social Engagement Level',
       'Income Level', 'Stress Levels', 'Urban vs Rural Living',
       'Alzheimer’s Diagnosis'],
      dtype='object')

In [42]:
df.dtypes

Country                                  object
Age                                       int64
Gender                                   object
Education Level                           int64
BMI                                     float64
Physical Activity Level                  object
Smoking Status                           object
Alcohol Consumption                      object
Diabetes                                 object
Hypertension                             object
Cholesterol Level                        object
Family History of Alzheimer’s            object
Cognitive Test Score                      int64
Depression Level                         object
Sleep Quality                            object
Dietary Habits                           object
Air Pollution Exposure                   object
Employment Status                        object
Marital Status                           object
Genetic Risk Factor (APOE-ε4 allele)     object
Social Engagement Level                 

In [43]:
df.isna().sum()

Country                                 0
Age                                     0
Gender                                  0
Education Level                         0
BMI                                     0
Physical Activity Level                 0
Smoking Status                          0
Alcohol Consumption                     0
Diabetes                                0
Hypertension                            0
Cholesterol Level                       0
Family History of Alzheimer’s           0
Cognitive Test Score                    0
Depression Level                        0
Sleep Quality                           0
Dietary Habits                          0
Air Pollution Exposure                  0
Employment Status                       0
Marital Status                          0
Genetic Risk Factor (APOE-ε4 allele)    0
Social Engagement Level                 0
Income Level                            0
Stress Levels                           0
Urban vs Rural Living             

In [44]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
for i in df.columns:
    if df[i].dtype=="object":
        df[i]=lab.fit_transform(df[i])
df

Country  Age  Gender  Education Level   BMI  Physical Activity Level  \
0           16   90       1                1  33.0                        2   
1            0   72       1                7  29.9                        2   
2           14   86       0               19  22.9                        0   
3            4   53       1               17  31.2                        1   
4           17   58       0                3  30.0                        0   
...        ...  ...     ...              ...   ...                      ...   
74278       12   60       0                3  22.6                        0   
74279       18   58       1               18  30.6                        1   
74280       16   57       0               13  28.2                        2   
74281        2   73       0                7  29.0                        1   
74282       11   57       0                1  31.7                        1   

       Smoking Status  Alcohol Consumption  Diabetes  Hypertension  ...  \
0                   2                    1         0             0  ...   
1                   1                    0         0             0  ...   
2                   0                    1         0             1  ...   
3                   2                    2         1             0  ...   
4                   1                    0         1             0  ...   
...               ...                  ...       ...           ...  ...   
74278               1                    0         0             0  ...   
74279               2                    1         1             0  ...   
74280               2                    2         0             0  ...   
74281               2                    2         0             0  ...   
74282               0                    2         0             0  ...   

       Dietary Habits  Air Pollution Exposure  Employment Status  \
0                   1                       0                  1   
1                   1                       2                  2   
2                   0                       2                  0   
3                   1                       2                  1   
4                   2                       0                  0   
...               ...                     ...                ...   
74278               0                       0                  2   
74279               0                       2                  2   
74280               1                       1                  0   
74281               1                       1                  0   
74282               0                       1                  2   

       Marital Status  Genetic Risk Factor (APOE-ε4 allele)  \
0                   1                                     0   
1                   2                                     0   
2                   1                                     0   
3                   1                                     0   
4                   0                                     0   
...               ...                                   ...   
74278               2                                     0   
74279               1                                     0   
74280               1                                     1   
74281               2                                     0   
74282               1                                     0   

       Social Engagement Level  Income Level  Stress Levels  \
0                            1             2              0   
1                            0             1              0   
2                            1             2              0   
3                            0             2              1   
4                            1             2              0   
...                        ...           ...            ...   
74278                        2             0              2   
74279                        2             0              0   
74280           

In [45]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)
x_train

array([[17., 77.,  0., ...,  0.,  2.,  0.],
       [11., 83.,  1., ...,  0.,  2.,  1.],
       [10., 52.,  1., ...,  2.,  2.,  0.],
       ...,
       [12., 60.,  0., ...,  0.,  1.,  1.],
       [15., 74.,  0., ...,  2.,  1.,  1.],
       [12., 88.,  1., ...,  0.,  2.,  0.]], shape=(51998, 24))

In [47]:
x_test

array([[15., 71.,  0., ...,  0.,  1.,  1.],
       [ 9., 88.,  1., ...,  2.,  2.,  0.],
       [ 6., 50.,  1., ...,  1.,  0.,  0.],
       ...,
       [16., 60.,  0., ...,  1.,  2.,  1.],
       [ 6., 80.,  0., ...,  1.,  1.,  0.],
       [ 6., 61.,  1., ...,  1.,  2.,  0.]], shape=(22285, 24))

In [48]:
y_train

array([0, 1, 0, ..., 0, 0, 1], shape=(51998,))

In [49]:
y_test

array([0, 1, 0, ..., 0, 0, 0], shape=(22285,))

In [50]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 1.30724952,  0.38962223, -0.99750302, ..., -1.2201221 ,
         1.21856053, -0.99884677],
       [ 0.26609523,  0.85146843,  1.00250323, ..., -1.2201221 ,
         1.21856053,  1.00115456],
       [ 0.09256952, -1.53473695,  1.00250323, ...,  1.23200595,
         1.21856053, -0.99884677],
       ...,
       [ 0.43962095, -0.91894202, -0.99750302, ..., -1.2201221 ,
        -0.00456337,  1.00115456],
       [ 0.96019809,  0.15869912, -0.99750302, ...,  1.23200595,
        -0.00456337,  1.00115456],
       [ 0.43962095,  1.23634026,  1.00250323, ..., -1.2201221 ,
         1.21856053, -0.99884677]], shape=(51998, 24))

In [51]:
x_test

array([[ 0.96019809, -0.07222398, -0.99750302, ..., -1.2201221 ,
        -0.00456337,  1.00115456],
       [-0.0809562 ,  1.23634026,  1.00250323, ...,  1.23200595,
         1.21856053, -0.99884677],
       [-0.60153334, -1.68868569,  1.00250323, ...,  0.00594192,
        -1.22768727, -0.99884677],
       ...,
       [ 1.1337238 , -0.91894202, -0.99750302, ...,  0.00594192,
         1.21856053,  1.00115456],
       [-0.60153334,  0.62054533, -0.99750302, ...,  0.00594192,
        -0.00456337, -0.99884677],
       [-0.60153334, -0.84196765,  1.00250323, ...,  0.00594192,
         1.21856053, -0.99884677]], shape=(22285, 24))

In [52]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0, 1, 0, ..., 0, 1, 0], shape=(22285,))

In [53]:
y_test

array([0, 1, 0, ..., 0, 0, 0], shape=(22285,))

In [54]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[10246,  2878],
       [ 3562,  5599]])

In [55]:
score=accuracy_score(y_test,y_pred)
score

0.7110163787300875