In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv("TravelInsurancePrediction.csv")
df

ID  Age               Employment Type GraduateOrNot  AnnualIncome  \
0        0   31             Government Sector           Yes        400000   
1        1   31  Private Sector/Self Employed           Yes       1250000   
2        2   34  Private Sector/Self Employed           Yes        500000   
3        3   28  Private Sector/Self Employed           Yes        700000   
4        4   28  Private Sector/Self Employed           Yes        700000   
...    ...  ...                           ...           ...           ...   
1982  1982   33  Private Sector/Self Employed           Yes       1500000   
1983  1983   28  Private Sector/Self Employed           Yes       1750000   
1984  1984   28  Private Sector/Self Employed           Yes       1150000   
1985  1985   34  Private Sector/Self Employed           Yes       1000000   
1986  1986   34  Private Sector/Self Employed           Yes        500000   

      FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0                 6                1            No                  No   
1                 7                0            No                  No   
2                 4                1            No                  No   
3                 3                1            No                  No   
4                 8                1           Yes                  No   
...             ...              ...           ...                 ...   
1982              4                0           Yes                 Yes   
1983              5                1            No                 Yes   
1984              6                1            No                  No   
1985              6                0           Yes                 Yes   
1986              4                0            No                  No   

      TravelInsurance  
0                   0  
1                   0  
2                   1  
3                   0  
4                   0  
...               ...  
1982                1  
1983                0  
1984                0  
1985                1  
1986                0  

[1987 rows x 10 columns]

In [3]:
df.head()

ID  Age               Employment Type GraduateOrNot  AnnualIncome  \
0   0   31             Government Sector           Yes        400000   
1   1   31  Private Sector/Self Employed           Yes       1250000   
2   2   34  Private Sector/Self Employed           Yes        500000   
3   3   28  Private Sector/Self Employed           Yes        700000   
4   4   28  Private Sector/Self Employed           Yes        700000   

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0              6                1            No                  No   
1              7                0            No                  No   
2              4                1            No                  No   
3              3                1            No                  No   
4              8                1           Yes                  No   

   TravelInsurance  
0                0  
1                0  
2                1  
3                0  
4                0

In [4]:
df.tail()

ID  Age               Employment Type GraduateOrNot  AnnualIncome  \
1982  1982   33  Private Sector/Self Employed           Yes       1500000   
1983  1983   28  Private Sector/Self Employed           Yes       1750000   
1984  1984   28  Private Sector/Self Employed           Yes       1150000   
1985  1985   34  Private Sector/Self Employed           Yes       1000000   
1986  1986   34  Private Sector/Self Employed           Yes        500000   

      FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
1982              4                0           Yes                 Yes   
1983              5                1            No                 Yes   
1984              6                1            No                  No   
1985              6                0           Yes                 Yes   
1986              4                0            No                  No   

      TravelInsurance  
1982                1  
1983                0  
1984                0  
1985                1  
1986                0

In [5]:
df.shape

(1987, 10)

In [6]:
df.columns

Index(['ID', 'Age', 'Employment Type', 'GraduateOrNot', 'AnnualIncome',
       'FamilyMembers', 'ChronicDiseases', 'FrequentFlyer',
       'EverTravelledAbroad', 'TravelInsurance'],
      dtype='object')

In [7]:
df.dtypes

ID                      int64
Age                     int64
Employment Type        object
GraduateOrNot          object
AnnualIncome            int64
FamilyMembers           int64
ChronicDiseases         int64
FrequentFlyer          object
EverTravelledAbroad    object
TravelInsurance         int64
dtype: object

In [8]:
df.isna().sum()

ID                     0
Age                    0
Employment Type        0
GraduateOrNot          0
AnnualIncome           0
FamilyMembers          0
ChronicDiseases        0
FrequentFlyer          0
EverTravelledAbroad    0
TravelInsurance        0
dtype: int64

In [9]:
df.drop(["ID"],axis=1,inplace=True)
df

Age               Employment Type GraduateOrNot  AnnualIncome  \
0      31             Government Sector           Yes        400000   
1      31  Private Sector/Self Employed           Yes       1250000   
2      34  Private Sector/Self Employed           Yes        500000   
3      28  Private Sector/Self Employed           Yes        700000   
4      28  Private Sector/Self Employed           Yes        700000   
...   ...                           ...           ...           ...   
1982   33  Private Sector/Self Employed           Yes       1500000   
1983   28  Private Sector/Self Employed           Yes       1750000   
1984   28  Private Sector/Self Employed           Yes       1150000   
1985   34  Private Sector/Self Employed           Yes       1000000   
1986   34  Private Sector/Self Employed           Yes        500000   

      FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0                 6                1            No                  No   
1                 7                0            No                  No   
2                 4                1            No                  No   
3                 3                1            No                  No   
4                 8                1           Yes                  No   
...             ...              ...           ...                 ...   
1982              4                0           Yes                 Yes   
1983              5                1            No                 Yes   
1984              6                1            No                  No   
1985              6                0           Yes                 Yes   
1986              4                0            No                  No   

      TravelInsurance  
0                   0  
1                   0  
2                   1  
3                   0  
4                   0  
...               ...  
1982                1  
1983                0  
1984                0  
1985                1  
1986                0  

[1987 rows x 9 columns]

In [10]:
from sklearn.preprocessing import LabelEncoder
encode=LabelEncoder()
df["Employment Type"]=encode.fit_transform(df["Employment Type"])
df["GraduateOrNot"]=encode.fit_transform(df["GraduateOrNot"])
df["FrequentFlyer"]=encode.fit_transform(df["FrequentFlyer"])
df["EverTravelledAbroad"]=encode.fit_transform(df["EverTravelledAbroad"])
df

Age  Employment Type  GraduateOrNot  AnnualIncome  FamilyMembers  \
0      31                0              1        400000              6   
1      31                1              1       1250000              7   
2      34                1              1        500000              4   
3      28                1              1        700000              3   
4      28                1              1        700000              8   
...   ...              ...            ...           ...            ...   
1982   33                1              1       1500000              4   
1983   28                1              1       1750000              5   
1984   28                1              1       1150000              6   
1985   34                1              1       1000000              6   
1986   34                1              1        500000              4   

      ChronicDiseases  FrequentFlyer  EverTravelledAbroad  TravelInsurance  
0                   1              0                    0                0  
1                   0              0                    0                0  
2                   1              0                    0                1  
3                   1              0                    0                0  
4                   1              1                    0                0  
...               ...            ...                  ...              ...  
1982                0              1                    1                1  
1983                1              0                    1                0  
1984                1              0                    0                0  
1985                0              1                    1                1  
1986                0              0                    0                0  

[1987 rows x 9 columns]

In [11]:
x=df.iloc[:,:-1].values
x

array([[31,  0,  1, ...,  1,  0,  0],
       [31,  1,  1, ...,  0,  0,  0],
       [34,  1,  1, ...,  1,  0,  0],
       ...,
       [28,  1,  1, ...,  1,  0,  0],
       [34,  1,  1, ...,  0,  1,  1],
       [34,  1,  1, ...,  0,  0,  0]], shape=(1987, 8))

In [12]:
y=df.iloc[:,-1].values
y

array([0, 0, 1, ..., 0, 1, 0], shape=(1987,))

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)
x_train

array([[34,  1,  0, ...,  0,  0,  0],
       [32,  0,  1, ...,  0,  0,  0],
       [29,  1,  1, ...,  0,  0,  0],
       ...,
       [26,  1,  1, ...,  1,  0,  0],
       [29,  1,  1, ...,  0,  0,  0],
       [25,  1,  0, ...,  0,  0,  0]], shape=(1390, 8))

In [14]:
x_test

array([[34,  1,  1, ...,  1,  1,  1],
       [28,  0,  1, ...,  1,  0,  0],
       [29,  1,  1, ...,  0,  0,  0],
       ...,
       [34,  1,  1, ...,  1,  0,  0],
       [29,  1,  1, ...,  0,  0,  0],
       [31,  0,  1, ...,  0,  1,  0]], shape=(597, 8))

In [15]:
y_train

array([0, 0, 0, ..., 1, 1, 0], shape=(1390,))

In [16]:
y_test

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [17]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[0.9, 1. , 0. , ..., 0. , 0. , 0. ],
       [0.7, 0. , 1. , ..., 0. , 0. , 0. ],
       [0.4, 1. , 1. , ..., 0. , 0. , 0. ],
       ...,
       [0.1, 1. , 1. , ..., 1. , 0. , 0. ],
       [0.4, 1. , 1. , ..., 0. , 0. , 0. ],
       [0. , 1. , 0. , ..., 0. , 0. , 0. ]], shape=(1390, 8))

In [18]:
x_test

array([[0.9, 1. , 1. , ..., 1. , 1. , 1. ],
       [0.3, 0. , 1. , ..., 1. , 0. , 0. ],
       [0.4, 1. , 1. , ..., 0. , 0. , 0. ],
       ...,
       [0.9, 1. , 1. , ..., 1. , 0. , 0. ],
       [0.4, 1. , 1. , ..., 0. , 0. , 0. ],
       [0.6, 0. , 1. , ..., 0. , 1. , 0. ]], shape=(597, 8))

In [19]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred


array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,

In [20]:
y_test

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[379,  20],
       [ 95, 103]])

In [22]:
score=accuracy_score(y_test,y_pred)
score

0.8073701842546064

In [23]:
from sklearn.metrics import classification_report 
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.80      0.95      0.87       399
           1       0.84      0.52      0.64       198

    accuracy                           0.81       597
   macro avg       0.82      0.74      0.76       597
weighted avg       0.81      0.81      0.79       597

